export const CONNECTION_REQUEST_SENT = "CONNECTION_REQUEST_SENT";
export const CONNECTION_REQUEST_SEND_FAILED = "CONNECTION_REQUEST_SEND_FAILED";

export const CONNECTION_REQUEST_RECEIVED = "CONNECTION_REQUEST_RECEIVED";

export const CONNECTION_REQUEST_ACCEPTED = "CONNECTION_REQUEST_ACCEPTED";
export const CONNECTION_REQUEST_ACCEPT_FAILED =
  "CONNECTION_REQUEST_ACCEPT_FAILED";

export const CONNECTION_REQUEST_REJECT = "CONNECTION_REQUEST_REJECT";
export const CONNECTION_REQUEST_REJECT_FAILED =
  "CONNECTION_REQUEST_REJECT_FAILED";

export const DISCONNECTED_USER = "DISCONNECTED_USER";
export const DISCONNECTED_USER_FAIL = "DISCONNECTED_USER_FAIL";
